[project]
name = "uv-lab-repo-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "s-missoum-ece", email = "sirine.missoum@edu.ece.fr" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
uv-lab-repo-git = "uv_lab_repo_git:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
